### ISSUE TITLE
main module status tracker

### ISSUE THREAD

**Issue by calacuda** [calacuda/synth-32#1]
tracking of the status of building the main keyboard module.

- [x] wave table sine wave oscillator
- [x] build test housing
- [x] solder knobs and switches
- [ ] finalize housing
- [ ] solder UART, I2S in, and I2S out, connectors
- [ ] add battery and power switch
